'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const fields=['representation','severity','incarcerated','guilty_plea','sentence_months'];
let rows=[],source='Synthetic demonstration',planText='';
function demo(){let seed=42;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};return Array.from({length:240},(_,i)=>{const representation=i<150?'aid':'private',severity=rand()<(representation==='aid'?.68:.4)?'higher':'lower',incarcerated=+(rand()<(severity==='higher'?.7:.28)),guilty_plea=+(rand()<.63),sentence_months=incarcerated?Math.round(8+rand()*60):0;return{representation,severity,incarcerated,guilty_plea,sentence_months};});}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function download(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function mean(r,key){return r.length?r.reduce((s,x)=>s+x[key],0)/r.length:null;}
function pct(n){return n===null?'Not available':(100*n).toFixed(1)+'%';}
function group(r,type){const a=r.filter(x=>x.representation===type),j=a.filter(x=>x.incarcerated);return{n:a.length,j:j.length,rate:mean(a,'incarcerated'),plea:mean(a,'guilty_plea'),months:mean(j,'sentence_months'),high:a.length?a.filter(x=>x.severity==='higher').length/a.length:null};}
function filtered(){return rows.filter(r=>$('#severity').value==='all'||r.severity===$('#severity').value);}
function research(){const r=filtered(),a=group(r,'aid'),p=group(r,'private');$('#dataset-label').textContent=source;$('#dataset-detail').textContent=source==='Synthetic demonstration'?'Illustrative cases, not the paper’s dataset. Descriptive comparisons are not causal effects.':'Uploaded records processed locally. Descriptive comparisons are not causal effects.';$('#stats').innerHTML=`<div class="stat"><span>Cases in view</span><strong>${r.length}</strong></div><div class="stat"><span>Legal-aid representation</span><strong>${a.n}</strong></div><div class="stat"><span>Private representation</span><strong>${p.n}</strong></div>`;$('#chart').innerHTML=[['Legal aid',a,''],['Private',p,'private']].map(([label,g,cl])=>`<div class="bar-row"><div class="bar-label"><span>${label}</span><strong>${pct(g.rate)}</strong></div><div class="track"><div class="bar ${cl}" style="width:${g.rate===null?0:100*g.rate}%"></div></div><small>${g.j} incarcerated / ${g.n} cases</small></div>`).join('');$('#comparison').textContent=a.n&&p.n?`Private minus aid: ${((p.rate-a.rate)*100).toFixed(1)} percentage points. This is an observed difference, not an estimated treatment effect.`:'Both groups need records to calculate a difference.';$('#balance').innerHTML=`<div class="balance-row">Higher-severity share · Legal aid<strong>${pct(a.high)}</strong></div><div class="balance-row">Higher-severity share · Private<strong>${pct(p.high)}</strong></div>`;$('#summary').innerHTML=[['Legal aid',a],['Private',p]].map(([label,g])=>`<tr><td>${label}</td><td>${g.n}</td><td>${pct(g.rate)}</td><td>${pct(g.plea)}</td><td>${g.months===null?'Not available':g.months.toFixed(1)+' months'}</td></tr>`).join('');}
function parseCSV(text){let records=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(!quoted&&cell.trim()!=='')throw Error('Unexpected quote in CSV.');else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell.trim());cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))records.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('Unclosed quote in CSV.');row.push(cell.trim());if(row.some(Boolean))records.push(row);if(records.length<2)throw Error('Include a header and at least one data row.');const head=records.shift().map(s=>s.replace(/^\uFEFF/,''));if(head.length!==5||new Set(head).size!==5||!fields.every(f=>head.includes(f)))throw Error('Use exactly the five columns listed in the CSV schema.');if(records.length>10000)throw Error('Use at most 10,000 rows.');return records.map((r,i)=>{if(r.length!==5)throw Error(`Row ${i+2}: expected five values.`);const o=Object.fromEntries(head.map((k,j)=>[k,r[j]]));if(!['aid','private'].includes(o.representation)||!['lower','higher'].includes(o.severity))throw Error(`Row ${i+2}: invalid representation or severity.`);for(const key of ['incarcerated','guilty_plea']){if(!['0','1'].includes(o[key]))throw Error(`Row ${i+2}: ${key} must be 0 or 1.`);o[key]=Number(o[key]);}if(o.sentence_months===''||!Number.isFinite(Number(o.sentence_months))||Number(o.sentence_months)<0)throw Error(`Row ${i+2}: invalid sentence months.`);o.sentence_months=Number(o.sentence_months);if(!o.incarcerated&&o.sentence_months!==0)throw Error(`Row ${i+2}: non-incarcerated cases must have zero sentence months.`);return o;});}
$$('[data-view]').forEach(b=>b.onclick=()=>{const view=b.dataset.view;$$('.view').forEach(v=>v.hidden=v.id!==view);$$('[data-view]').forEach(n=>{n.classList.toggle('active',n===b);n.setAttribute('aria-current',n===b?'page':'false');});});
$('#csv').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error('Choose a CSV smaller than 2 MB.');const parsed=parseCSV(await file.text());rows=parsed;source='Uploaded dataset';$('#severity').value='all';research();$('#import-status').textContent=`Imported ${rows.length} valid records. No records were sent to a server.`;}catch(err){$('#import-status').textContent=err.message+' Existing dataset unchanged.';}finally{e.target.value='';}};
$('#template').onclick=()=>download('aid-atlas-synthetic-sample.csv',fields.join(',')+'\n'+demo().map(r=>fields.map(f=>r[f]).join(',')).join('\n'),'text/csv');$('#reset-data').onclick=()=>{rows=demo();source='Synthetic demonstration';$('#severity').value='all';$('#import-status').textContent='Demo restored.';research();};$('#severity').onchange=research;
$('#export').onclick=()=>{const r=filtered(),a=group(r,'aid'),p=group(r,'private');download('aid-atlas-analysis.json',JSON.stringify({created:new Date().toISOString(),source,severityFilter:$('#severity').value,method:'Unadjusted descriptive group summaries. Not causal inference.',cases:r.length,aid:a,private:p,incarcerationDifferencePercentagePoints:a.n&&p.n?(p.rate-a.rate)*100:null,limitations:['Nonrandom representation assignment','No covariate adjustment','No confidence intervals','Sentence length conditional on incarceration','No individual prediction']},null,2),'application/json');};
$('#planner').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),stage=f.get('stage'),income=f.get('income');const tasks=['Gather the letters, notices, and documents you have about your matter.','Prepare a summary of income, assets, debts, and regular expenses to discuss with the service.'];tasks.push(income==='employed'?'Gather recent payslips or other evidence of earnings.':income==='benefits'?'Gather recent benefit statements.':income==='variable'?'Gather records showing variable income and business expenses.':'Prepare to explain how you currently meet living expenses.');if(f.has('dependants'))tasks.push('Make a list of dependants and the support expenses you pay.');if(f.has('interpreter'))tasks.push('Ask the service how to arrange an interpreter in your preferred language.');if(f.has('access'))tasks.push('Tell the service what accessibility adjustments would help you participate.');if(stage==='denied')tasks.push('Keep the refusal letter. Ask the service to explain the reason, whether a review is available, and any applicable deadline.');else if(stage==='waiting')tasks.push('Keep your application reference privately and ask whether any information is missing.');else tasks.push('Ask your chosen service which application form and supporting documents it requires.');const date=f.get('date');let dateText=date?`Appointment or court date: ${date}. Confirm the date and any filing deadlines with your adviser.`:'No date entered. Check your correspondence for appointments and deadlines.';if(date&&date<new Date().toLocaleDateString('en-CA'))dateText+=' This date appears to be in the past; check it before using this plan.';const questions=['Does your service cover this type of matter and location?','Which eligibility criteria apply to my circumstances?','What should I do before my next appointment or court date?'];planText=`Aid Atlas — Preparation checklist\nMatter: ${f.get('matter')}\n${dateText}\n\n`+tasks.map(t=>'[ ] '+t).join('\n')+'\n\nQuestions to ask\n'+questions.map(q=>'- '+q).join('\n')+'\n\nThis is a preparation aid, not an eligibility decision, legal advice, or submitted application.';$('#plan-output').innerHTML=`<p class="eyebrow">Your preparation plan</p><h2>${tasks.length} things to prepare</h2><p>${esc(dateText)}</p>${tasks.map(t=>`<label class="task-item"><input type="checkbox"><span>${esc(t)}</span></label>`).join('')}<h3>Questions for your adviser</h3><ul>${questions.map(q=>`<li>${q}</li>`).join('')}</ul><div class="plan-actions"><button id="download-plan" type="button">Download checklist</button><button id="clear-plan" type="button">Clear answers</button></div><p class="caption">Completion ticks are for this session. The download contains the complete checklist.</p>`;$('#download-plan').onclick=()=>download('my-legal-aid-preparation.txt',planText);$('#clear-plan').onclick=()=>{e.target.reset();planText='';$('#plan-output').innerHTML='<h2>Answers cleared.</h2><p>Create a new checklist whenever you are ready.</p>';};};
function capacity(){const b=Number($('#budget').value),c=Number($('#cost').value),d=Number($('#demand').value),h=Number($('#hours').value);$('#hours-label').textContent=h+' h';if(!$('#capacity-form').checkValidity()){$('#capacity-values').innerHTML='<p class="error">Enter positive values within the allowed ranges.</p>';return;}const available=Math.floor(b/(c*h)),served=Math.min(available,d),unserved=Math.max(0,d-served);$('#capacity-values').innerHTML=`<div class="big-number">${served.toLocaleString()}<span>applications with funded casework capacity</span></div><div class="track"><div class="bar" style="width:${100*served/d}%"></div></div><p>${(100*served/d).toFixed(1)}% of assumed demand can be covered.</p><div class="capacity-metrics"><div><strong>${unserved.toLocaleString()}</strong><span>applications beyond capacity</span></div><div><strong>$${(c*h).toLocaleString()}</strong><span>assumed cost per case</span></div></div><p class="caption">Formula: floor(budget ÷ hourly cost ÷ hours per case), capped at demand.</p>`;}
$('#capacity-form').oninput=capacity;$('#capacity-form').onsubmit=e=>e.preventDefault();rows=demo();research();capacity();

function openHashView(){const id=location.hash.slice(1);const button=document.querySelector(`[data-view="${CSS.escape(id)}"]`);if(button)button.click();}
window.addEventListener("hashchange",openHashView);openHashView();
