'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fields=['branch_id','period','intakes','completed','staff_minutes','recontacts','referrals','accepted_referrals'];
let state=null,society='pilot',evidence=null,poll=null;
const stamp=s=>s?new Date(s).toLocaleString():'Not yet checked';
function tell(t,error=false){$('#global-status').textContent=t;$('#global-status').classList.toggle('error',error);}
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-Aid-Atlas':'local'}:{},body:body?JSON.stringify({...body,society}):undefined});let data;try{data=await response.json();}catch{throw Error('The research server is not running. Start server.py to use persistent tools.');}if(!response.ok)throw Error(data.error||'Request failed');return data;}
function file(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function sum(rows,k){return rows.reduce((s,r)=>s+r[k],0);}function percent(a,b){return b?(a/b*100).toFixed(1)+'%':'Not available';}
function selected(){return state.metrics.filter(r=>($('#period').value==='all'||r.period===$('#period').value)&&($('#branch').value==='all'||r.branch_id===$('#branch').value));}
function totals(rows){const keys=fields.slice(2),out={};keys.forEach(k=>out[k]=sum(rows,k));return out;}
function overview(){const rows=selected(),t=totals(rows);const origins=[...new Set(rows.map(r=>r.origin))];$('#origin-label').textContent=origins.join(' + ')||'No rows in this view';$('#metrics').innerHTML=[['Received intakes',t.intakes.toLocaleString()],['Completed intake',percent(t.completed,t.intakes)],['Staff minutes / completed',t.completed?(t.staff_minutes/t.completed).toFixed(1):'Not available'],['Referral acceptance',percent(t.accepted_referrals,t.referrals)]].map(([a,b])=>`<div class="metric"><span>${a}</span><strong>${b}</strong></div>`).join('');const groups=state.branches.map(b=>({...b,...totals(rows.filter(r=>r.branch_id===b.id))})).filter(b=>b.intakes>0);$('#branch-chart').innerHTML=groups.length?groups.map(b=>`<div class="chart-row"><div class="chart-label"><span>${esc(b.name)}</span><span>${percent(b.completed,b.intakes)} · ${b.completed}/${b.intakes}</span></div><div class="track"><div class="bar" style="width:${100*b.completed/b.intakes}%"></div></div></div>`).join(''):'<p class="fine">No branch records match this filter. Import aggregate metrics or change the period.</p>';const signal=[];if(t.intakes)signal.push(`<div class="signal"><strong>${t.intakes-t.completed} intakes not yet completed in these records</strong><p>Inspect missing information and follow-up workload. This count is not a legal-aid refusal count.</p></div>`);if(t.recontacts)signal.push(`<div class="signal"><strong>${t.recontacts} repeat-contact events</strong><p>Review which intake fields or communication barriers trigger follow-up. Events may include multiple contacts for the same application.</p></div>`);if(t.referrals)signal.push(`<div class="signal"><strong>${t.referrals-t.accepted_referrals} referrals without recorded acceptance</strong><p>Check destination capacity and whether acknowledgement is missing before calling these unresolved.</p></div>`);$('#signals').innerHTML=signal.join('')||'<p class="fine">Add aggregate records to generate descriptive signals.</p>';const names=Object.fromEntries(state.branches.map(b=>[b.id,b.name]));$('#records').innerHTML=rows.map(r=>`<tr><td>${esc(names[r.branch_id])}</td><td>${esc(r.period)}</td><td>${r.intakes}</td><td>${r.completed}</td><td>${r.staff_minutes}</td><td>${r.recontacts}</td><td>${r.accepted_referrals}/${r.referrals}</td></tr>`).join('');}
function research(){const running=state.jobs.some(j=>j.status==='running');$('#refresh-sources').disabled=running;$('#refresh-sources').textContent=running?'Checking approved sources…':'Refresh approved sources';$('#auto-refresh').checked=state.auto_refresh;$('#source-cards').innerHTML=state.sources.map(s=>`<article class="source-card"><span class="status">${s.versions} saved ${s.versions===1?'version':'versions'}</span><h3>${esc(s.title)}</h3><p>${esc(s.scope)}</p><p>Last check: ${esc(stamp(s.last_checked))}</p>${s.last_error?`<p class="error">Refresh failed: ${esc(s.last_error)}</p>`:''}<a href="${esc(s.url)}" target="_blank" rel="noopener">Original source ↗</a><button data-source="${s.id}" ${s.versions?'':'disabled'}>Inspect saved evidence</button></article>`).join('');$('#jobs').innerHTML=state.jobs.length?state.jobs.slice(0,3).map(j=>{let result=[];try{result=JSON.parse(j.result||'[]');}catch{}return `<div class="audit-item"><strong>${esc(j.status.replaceAll('_',' '))}</strong> · ${esc(stamp(j.started_at))}${result.map(r=>`<small>${esc(r.source)}: ${esc(r.status)}${r.error?' — '+esc(r.error):''}</small>`).join('')}</div>`;}).join(''):'<p class="fine">No refresh has run. Use “Refresh approved sources” to fetch and store source text.</p>';$('#review-queue').innerHTML=state.reviews.length?state.reviews.map(r=>`<div class="review-row"><div><strong>${esc(r.title)}</strong><p>Version ${r.snapshot_id} · ${esc(r.status.replaceAll('_',' '))} · ${esc(stamp(r.created_at))}</p></div><div class="actions"><button data-source="${r.source_id}" data-snapshot="${r.snapshot_id}">Inspect this version</button><button data-review="${r.id}" ${r.status==='acknowledged'?'disabled':''}>${r.status==='acknowledged'?'Acknowledged':'Acknowledge review'}</button></div></div>`).join(''):'<p class="fine">First snapshots and changed sources will appear here after a successful refresh.</p>';if(running&&!poll)poll=setInterval(()=>load(false).catch(e=>tell(e.message,true)),2500);if(!running&&poll){clearInterval(poll);poll=null;}}
function policies(){$('#policy-list').innerHTML=state.policies.length?state.policies.map(p=>`<div class="policy-record"><span class="status">Draft · ${esc(stamp(p.created_at))}</span><h3>${esc(p.title)}</h3><p>${esc(p.body)}</p></div>`).join(''):'<p class="fine">No drafts for this society. Capture a proposal using a metric or a reviewed source as its starting point.</p>';$('#audit').innerHTML=state.audit.length?state.audit.map(a=>`<div class="audit-item">${esc(a.detail)}<small>${esc(a.action)} · ${esc(stamp(a.created_at))}</small></div>`).join(''):'<p class="fine">No saved actions for this society yet.</p>';}
async function load(resetFilters=false){const requested=society;const next=await api('/api/bootstrap?society='+encodeURIComponent(requested));if(requested!==society)return;state=next;if(resetFilters){$('#period').innerHTML='<option value="all">All periods</option>'+[...new Set(state.metrics.map(r=>r.period))].sort().map(p=>`<option>${esc(p)}</option>`).join('');$('#branch').innerHTML='<option value="all">All branches</option>'+state.branches.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('');}overview();research();policies();renderMatters();}
$$('[data-pane]').forEach(b=>b.onclick=()=>{$$('.pane').forEach(p=>p.hidden=p.id!==b.dataset.pane);$$('[data-pane]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-current',x===b?'page':'false');});});
$('#society').onchange=async e=>{society=e.target.value;resetMatter();$('#policy-form').reset();try{await load(true);tell('Society filter changed. All demo societies remain accessible to this local operator.');}catch(err){tell(err.message,true);}};$('#period').onchange=overview;$('#branch').onchange=overview;
$('#refresh-sources').onclick=async()=>{try{await api('/api/research/refresh',{});tell('Public-source refresh started. Results will update automatically.');await load();}catch(e){tell(e.message,true);}};$('#auto-refresh').onchange=async e=>{try{await api('/api/settings',{auto_refresh:e.target.checked});tell(e.target.checked?'Six-hour monitoring enabled while this local server is running.':'Automatic monitoring paused.');await load();}catch(err){tell(err.message,true);e.target.checked=!e.target.checked;}};
document.addEventListener('click',async e=>{const source=e.target.closest('[data-source]'),review=e.target.closest('[data-review]');if(source){try{evidence=await api('/api/source?id='+encodeURIComponent(source.dataset.source)+(source.dataset.snapshot?'&snapshot='+source.dataset.snapshot:''));$('#evidence-date').textContent='Captured: '+stamp(evidence.created_at);$('#evidence-content').textContent=evidence.text;$('#evidence-dialog').showModal();}catch(err){tell(err.message,true);}}if(review){try{await api('/api/reviews/acknowledge',{id:Number(review.dataset.review)});await load();tell('Source review acknowledged by the local operator. No internal policy was changed.');}catch(err){tell(err.message,true);}}const view=e.target.closest('[data-evidence-view]');if(view&&evidence)$('#evidence-content').textContent=evidence[view.dataset.evidenceView]||'No differences available.';});
$('#policy-form').onsubmit=async e=>{e.preventDefault();try{await api('/api/policies',{title:$('#policy-title').value,body:$('#policy-body').value});e.target.reset();await load();tell('Policy draft saved locally for this society.');}catch(err){tell(err.message,true);}};
function parseCSV(text){const records=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++;}else if(!q&&cell.trim())throw Error('Unexpected quote.');else q=!q;}else if(c===','&&!q){row.push(cell.trim());cell='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))records.push(row);row=[];cell='';}else cell+=c;}if(q)throw Error('Unclosed CSV quote.');row.push(cell.trim());if(row.some(Boolean))records.push(row);const header=(records.shift()||[]).map(x=>x.replace(/^\uFEFF/,''));if(header.length!==fields.length||new Set(header).size!==fields.length||!fields.every(f=>header.includes(f)))throw Error('Use exactly the eight template columns.');return records.map((r,i)=>{if(r.length!==fields.length)throw Error(`Row ${i+2} has the wrong number of fields.`);const o={};header.forEach((k,j)=>{if(r[j]==='')throw Error(`Row ${i+2} has an empty field.`);o[k]=j>=0&&['branch_id','period'].includes(k)?r[j]:Number(r[j]);});return o;});}
$('#download-metrics').onclick=()=>{if(!state)return;file('aid-atlas-aggregate-template.csv',fields.join(',')+'\n'+state.metrics.map(r=>fields.map(f=>r[f]).join(',')).join('\n'),'text/csv');};$('#metrics-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2000000)throw Error('Use a CSV smaller than 2 MB.');const rows=parseCSV(await f.text());const r=await api('/api/metrics/import',{rows});await load(true);tell(`${r.imported} aggregate rows saved. Matching branch-month records were replaced.`);}catch(err){tell(err.message+' No partial import was saved.',true);}finally{e.target.value='';}};
$('#report').onclick=()=>{if(!state)return;file('aid-atlas-operational-report.json',JSON.stringify({created:new Date().toISOString(),society,filters:{period:$('#period').value,branch:$('#branch').value},totals:totals(selected()),records:selected(),method:'Descriptive aggregate branch-month analysis. Not causal inference.',limitations:['Demo rows are synthetic','Completion is intake completion, not legal-aid approval','Case mix and workflow definitions may differ','Repeated contacts count events, not unique people']},null,2),'application/json');};
function storage(e){e.preventDefault();$('#storage-dialog').showModal();}$('#storage-link').onclick=storage;$('#storage-button').onclick=storage;$$('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());load(true).catch(e=>tell(e.message+' Start the local backend with python3 server.py.',true));

let editingMatter=null;
function resetMatter(){editingMatter=null;$('#matter-form').reset();$('#matter-form-title').textContent='New matter';}
function renderMatters(){const previous=$('#matter-branch').value;$('#matter-branch').innerHTML=state.branches.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('');if(state.branches.some(b=>b.id===previous))$('#matter-branch').value=previous;const q=$('#matter-search').value.toLowerCase(),stage=$('#matter-filter').value;const rows=(state.matters||[]).filter(m=>(!stage||m.stage===stage)&&[m.title,m.owner].join(' ').toLowerCase().includes(q));$('#matter-list').innerHTML=rows.length?rows.map(m=>`<article class="policy-record"><span class="status">${esc(m.stage)} · #${m.id}</span><h3>${esc(m.title)}</h3><p>${esc(m.owner||'Unassigned')} · ${esc(state.branches.find(b=>b.id===m.branch_id)?.name||m.branch_id)}</p><p>${m.due?'Due '+esc(m.due):'No due date'}</p><button type="button" data-matter="${m.id}">Open matter</button></article>`).join(''):'<p class="fine">No matters match. Create a de-identified matter to begin.</p>';}
$('#new-matter').onclick=resetMatter;$('#matter-search').oninput=()=>state&&renderMatters();$('#matter-filter').onchange=()=>state&&renderMatters();
document.addEventListener('click',e=>{const b=e.target.closest('[data-matter]');if(!b)return;const m=state.matters.find(m=>m.id===Number(b.dataset.matter));if(!m)return;editingMatter=m.id;for(const k of ['title','owner','stage','due','notes'])$('#matter-'+k).value=m[k];$('#matter-branch').value=m.branch_id;$('#matter-form-title').textContent='Edit matter #'+m.id;});
$('#matter-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;try{const body={branch_id:$('#matter-branch').value};for(const k of ['title','owner','stage','due','notes'])body[k]=$('#matter-'+k).value;if(editingMatter!==null)body.id=editingMatter;await api('/api/matters',body);resetMatter();await load();tell('Matter saved locally.');}catch(err){tell(err.message,true);}finally{button.disabled=false;}};
